### ISSUE TITLE
Possible issue when serving under a subdirectory?

### ISSUE THREAD

**Issue by hideya** [maru-labo/doodle#1]
https://github.com/maru-labo/doodle/blob/21137fc14c9d3789209d0e2ca5752fda910d32c6/examples/tensorflow_js/src/index.js#L12

In the lecture, an attendee may serve this app from a subdirectory assigned by a lecturer.
So, I thought the line could better be like the following.  What do you think?
```js
const href = window.location.href;
const pref = href.substring(0, href.lastIndexOf('/'));
```

**Comment by ornew** [comment]
Hi, Thanks for your comment 👍 

Yes, this example can NOT be served from a subdirectory now.

However, I think that this example should be generic. There are few cases where model data is stored in a relative position from the current URL.

In the lecture, I think it would be better to let participants edit the following parts:

1. model-url
2. weights-url
3. labels

How about it?

**Comment by hideya** [comment]
Sounds good to me!
I'll close this as not-an-issue.
