### ISSUE TITLE
[doodle.ipynb] Itemized list's numbers  slipping off by one

### ISSUE THREAD

**Issue by hideya** [maru-labo/doodle#13]
Comments on Jupyter notebook in Japanese.

to: @ornew 

以下の Itemized List ですが、コードでは「０」からスタートしているのに、Markdownでの実際の表示は、自動的に「１」からに変更されちゃってます（githubのMarkdownでもJupyter notebookのものでも。ちなみに、List の先頭を全部「1.」にしても、１から５に書き換えられます）。

https://github.com/maru-labo/doodle/blob/3e00f0221ebdd6de4dd49eaf48a50e7e64588b15/docs/doodle.ipynb#L70-L74

実際の表示は以下のようになってます。
![output](https://i.imgur.com/nOVjOHm.png)

結果、「1-3を繰り返す」の部分のステップの指定が、１ズレてしまっています。
加えて、以下の図の①②③ともずれてしまっています。

![e](https://raw.githubusercontent.com/maru-labo/doodle/3e00f0221ebdd6de4dd49eaf48a50e7e64588b15/docs/img/2.png)

**Comment by ornew** [comment]
ありがとうございます。非連番リストに変えて数字を書くように直します。

**Comment by ornew** [comment]
Completed: 9ce158f0d7684792201efcf58b1359258d0ef91a
close.
