### ISSUE TITLE
Should not include model binaries in the repository.

### ISSUE THREAD

**Issue by ornew** [maru-labo/doodle#17]
@hideya 
Currently it seems that the repository contains model binaries(`example/tensorflow_js_simple/public`). This is undesirable. When model data exceeding 200 MB is kept committed, git becomes very heavy.

Model data is included in the [release](https://github.com/maru-labo/doodle/releases/latest). Please change the usage so that model data is downloaded separately. If you need to fixture the model data version, you can explicitly specify the release tag version.

When change of usage is confirmed, I delete the binary data by going back to the history.
Sorry to trouble you, but thank you.

**Comment by hideya** [comment]
Good point!  Thanks for the comment.  I've fixed the issue in PR https://github.com/maru-labo/doodle/pull/18
Once merged, please go ahead and remove the binary data from the commit history.
Sorry for the trouble...

**Comment by ornew** [comment]
@hideya 
Thank you for your response! I deleted the binary by tracing the history.
This was a very dangerous operation. Please fork the repository again.

**Comment by hideya** [comment]
Thank you. Glad that you have done it before  the hands on.  Appreciate it!
