### ISSUE TITLE
Maybe better to have tf.tidy() around tensor operations?

### ISSUE THREAD

**Issue by hideya** [maru-labo/doodle#7]
The following lines involves tensor operations, including creating temporary ones.

https://github.com/maru-labo/doodle/blob/2f6b3143b02d86b965767cd9d6380fa7ce5a2e85/examples/tensorflow_js/src/cmps/doodle.vue#L74-L80

Checking google's example code like the following, `tf.tidy()` is used around such operations:

https://github.com/tensorflow/tfjs-examples/blob/bf51024bd04fa6197b410db10e5210d4604aef43/mnist/index.js#L114-L122

I'm wondering whether it is needed for this case, although I realize that the tensor that hold the result is explicitly disposed, so there maybe no need for `tf.tidy()`.

https://github.com/maru-labo/doodle/blob/2f6b3143b02d86b965767cd9d6380fa7ce5a2e85/examples/tensorflow_js/src/cmps/doodle.vue#L70

Still, it might be easier for beginners to read the code as a reference if `tf.tidy()` is used instead of the explicit `dispose()`.

I'm creating this issue, just in case.

**Comment by ornew** [comment]
Thank you! Fix to use `tf.tidy()`. 8c91e6c
